#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("spoty.Resource", IsApplication=true)]

namespace spoty
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001a
			public const int buttonExit = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int buttonLogin = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int buttonLoginGuest = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int buttonLogout = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int buttonRate = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int editTextFeedback = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int editTextPassword = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int editTextUsername = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int imageViewLogin = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int linearLayoutLogin = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int listViewLocations = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int listViewRatings = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int ratingBarLocation = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int tableLayoutLocation = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int tableRowCity = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int tableRowCountry = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int tableRowCounty = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int tableRowName = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int tableRowStreet = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int tableRowType = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int textViewCity = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int textViewCountry = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int textViewCounty = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int textViewName = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int textViewStreet = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int textViewType = 2131034117;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LocationDetailLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LocationOverviewLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int LocationDetailLayoutTitle = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int LocationOverviewLayoutTitle = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int LoginLayoutTitle = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
